base_dir: tmpbs5q4d7x
project: my_first_swmm
bbox:
- 1.5274
- 42.50524
- 1.54273
- 42.51259
run_settings:
  duration: 3600
graphfcn_list:
- assign_id
- fix_geometries
- remove_non_pipe_allowable_links
- calculate_streetcover
- remove_parallel_edges
- to_undirected
- split_long_edges
- merge_street_nodes
- assign_id
- clip_to_catchments
- calculate_contributing_area
- set_elevation
- double_directed
- fix_geometries
- set_surface_slope
- set_chahinian_slope
- set_chahinian_angle
- calculate_weights
- identify_outfalls
- derive_topology
- pipe_by_pipe
- fix_geometries
- assign_id
metric_list:
- outfall_nse_flow
- outfall_kge_flow
- outfall_relerror_flow
- outfall_relerror_length
- outfall_relerror_npipes
- outfall_relerror_nmanholes
- outfall_relerror_diameter
- outfall_nse_flooding
- outfall_kge_flooding
- outfall_relerror_flooding
- grid_nse_flooding
- grid_kge_flooding
- grid_relerror_flooding
- subcatchment_nse_flooding
- subcatchment_kge_flooding
- subcatchment_relerror_flooding
- bias_flood_depth
- kstest_edge_betweenness
- kstest_betweenness
- outfall_kstest_diameters
- nc_deltacon0
- nc_laplacian_dist
- nc_vertex_edge_distance
address_overrides:
  precipitation: C:\Users\bdobson\Documents\GitHub\SWMManywhere\src\swmmanywhere\defs\storm.dat
parameter_overrides:
  topology_derivation:
    allowable_networks:
    - drive
    omit_edges:
    - bridge
  outfall_derivation:
    outfall_length: 5
    river_buffer_distance: 30
