name: Test

on: 
  workflow_call:
    secrets:
      codecov_token:
        required: true
    inputs:
      os:
        description: 'Operating system'
        default: '["ubuntu-latest", "windows-latest"]'
        type: string
      python-version:
        description: 'Python version'
        default: '["3.10"]'
        type: string

jobs:
  paper:
    runs-on: ubuntu-latest
    needs: publish-PyPI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: docs/paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: docs/paper/paper.pdf

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{fromJson(inputs.os)}}
        python-version: ${{fromJson(inputs.python-version)}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -e .[dev]

    - name: Run tests
      run: pytest

    - name: Upload coverage to Codecov
      if: success() && (matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10')
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.codecov_token }}
        verbose: true
