name: Test

on: 
  workflow_call:
    inputs:
      os:
        description: 'Operating system'
        default: '["ubuntu-latest", "windows-latest"]'
        type: string
      python-version:
        description: 'Python version'
        default: '["3.10"]'
        type: string

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{fromJson(inputs.os)}}
        python-version: ${{fromJson(inputs.python-version)}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install .[dev]

    - name: Run tests
      run: pytest --junitxml=junit/pytest.xml \
        --cov=swmmanywhere \
        --cov-branch \
        --cov-report=xml

    - name: Upload coverage to Codecov
      if: success() && (github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10')
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        files: ./coverage.xml
        verbose: true